CREATE SCHEMA IF NOT EXISTS mentorship;

CREATE TABLE IF NOT EXISTS mentorship.mentorships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_email VARCHAR(320) NOT NULL,
    student_email VARCHAR(320),
    area_of_expertise VARCHAR(500),
    status VARCHAR(32) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mentorships_mentor ON mentorship.mentorships (mentor_email);
CREATE INDEX IF NOT EXISTS idx_mentorships_pair ON mentorship.mentorships (student_email, mentor_email);

CREATE TABLE IF NOT EXISTS mentorship.mentor_availability (
    mentor_email VARCHAR(320) NOT NULL PRIMARY KEY,
    available BOOLEAN NOT NULL DEFAULT FALSE
);
