-- Canonical DDL mirror of services/mentorship-service/src/main/resources/db/migration/V1__mentorship_schema.sql
-- Applied at runtime by Flyway.

CREATE SCHEMA IF NOT EXISTS mentorship;

CREATE TABLE mentorship.mentorships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_email VARCHAR(320) NOT NULL,
    student_email VARCHAR(320),
    area_of_expertise VARCHAR(500),
    status VARCHAR(32) NOT NULL
);

CREATE INDEX idx_mentorships_mentor ON mentorship.mentorships (mentor_email);
CREATE INDEX idx_mentorships_pair ON mentorship.mentorships (student_email, mentor_email);

CREATE TABLE mentorship.mentor_availability (
    mentor_email VARCHAR(320) NOT NULL PRIMARY KEY,
    available BOOLEAN NOT NULL DEFAULT FALSE
);
