-- Mirror of event-service Flyway migrations (see services/event-service/src/main/resources/db/migration/).

CREATE SCHEMA IF NOT EXISTS event;

CREATE TABLE IF NOT EXISTS event.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    event_date VARCHAR(64),
    description TEXT
);

CREATE TABLE IF NOT EXISTS event.event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    registrant_email VARCHAR(320) NOT NULL,
    registered_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_event_registrations_event FOREIGN KEY (event_id) REFERENCES event.events (id) ON DELETE CASCADE,
    CONSTRAINT uq_event_registrant UNIQUE (event_id, registrant_email)
);
